# .github/workflows/ci.yml

# Workflow name
name: CI

# Event for the workflow
on: push

# List of jobs
jobs:
  build:
    name: Lint, Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ORG_READ_PACKAGES_TOKEN }}
        with:
          registry-url: 'https://npm.pkg.github.com'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --coverage --passWithNoTests

      - name: Build
        run: yarn build
